In [ ]:
import numpy as np


arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(0,10)  # 0 bis 9
arr3 = np.zeros(5)      # [0. 0. 0. 0. 0.]
arr5 = np.full(8, 3)    # 8 mal die 3 
print(arr1, arr2, arr3, arr5)



[1 2 3 4 5] [0 1 2 3 4 5 6 7 8 9] [0. 0. 0. 0. 0.] [3 3 3 3 3 3 3 3]


In [ ]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", b.shape) #gibt an wie viele zeilen und spalten
print("Zugriff auf Element:", b[0, 2]) #element in der ersten zeile an der stelle 2(gezählt wird von 0)

Shape: (2, 3)
Zugriff auf Element: 3


In [ ]:
arr = np.array([3,4,5,6,7,8,9])
print(arr[2:6:2]) #von 5 bis 8 in 2 schritte: 5, 7
print(arr[2:6]) # von 5 bis 8 alles ausgeben

[5 7]
[5 6 7 8]


In [ ]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mat + 10) # alle Elemente werden um 10 addiert
print(mat * 2) # alle elemente werden um 2 multiziplizert
print("Mittelwert:", np.mean(mat)) 
print("Standardabweichung:", np.std(mat))

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Mittelwert: 5.0
Standardabweichung: 2.581988897471611


In [29]:
arr = np.array([12, 15, 20, 10, 8, 13])
print("Mittelwert:", np.mean(arr))
print("Standardabweichung:", np.std(arr))
print(arr + 5)

Mittelwert: 13.0
Standardabweichung: 3.8297084310253524
[17 20 25 15 13 18]


In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr1d = np.array([1,2,3])
print(mat + arr1d)  # Broadcasting auf Zeilen



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
arr5 = np.arange(12).reshape(3,4) # von 0 bis 11. 3 zeilen mit jeweils 4 einträgen
print(arr5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
# Übung: Grundrechenoperationen & Statistik in NumPy

arr = np.random.randint(1, 10, size = (3,4))  # 3 Reihen, 4 Spalten
print(arr)
print("Quadrat **2:\n", arr ** 2)

print("Mittelwert gesamt:", np.mean(arr))
print("Mittelwert pro Spalte:", np.mean(arr, axis=0))
print("Mittelwert pro Zeile:", np.mean(arr, axis=1))

print("Summe gesamt:", np.sum(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))




[[8 7 1 4]
 [1 8 2 9]
 [4 4 9 7]]
Quadrat **2:
 [[64 49  1 16]
 [ 1 64  4 81]
 [16 16 81 49]]
Mittelwert gesamt: 5.333333333333333
Mittelwert pro Spalte: [4.33333333 6.33333333 4.         6.66666667]
Mittelwert pro Zeile: [5. 5. 6.]
Summe gesamt: 64
Minimum: 1
Maximum: 9


In [2]:
import numpy as np
arr = np.random.randint(1, 21, size = (3,5))
print(arr)
print("Mittwelert pro Zeile:\n", np.mean(arr, axis=1))
print("Standardabweichung pro Spalte:\n", np.std(arr, axis=0))
print("Gesamtsumme:", np.sum(arr))

[[ 6 16 12 19 17]
 [11 17 12  7  4]
 [ 7  4  3 17  7]]
Mittwelert pro Zeile:
 [14.  10.2  7.6]
Standardabweichung pro Spalte:
 [2.1602469  5.90668172 4.24264069 5.24933858 5.55777733]
Gesamtsumme: 159
