In [ ]:
import numpy as np


arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(0,10)  # 0 to 9
arr3 = np.zeros(5)      # [0. 0. 0. 0. 0.]
arr5 = np.full(8, 3)    # 8 times the 3
print(arr1, arr2, arr3, arr5)



[1 2 3 4 5] [0 1 2 3 4 5 6 7 8 9] [0. 0. 0. 0. 0.] [3 3 3 3 3 3 3 3]


In [ ]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", b.shape) #specifies how many rows and columns
print("Access item:", b[0, 2]) #element in the first row at position 2 (counting starts from 0)

Shape: (2, 3)
Zugriff auf Element: 3


In [ ]:
arr = np.array([3,4,5,6,7,8,9])
print(arr[2:6:2]) # from 5 to 8 in 2 steps: 5, 7
print(arr[2:6]) # give everything from 5 to 8.

[5 7]
[5 6 7 8]


In [ ]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mat + 10) # All elements are added together by 10.
print(mat * 2) # All elements are multiplied by 2.
print("mean:", np.mean(mat)) 
print("Standard deviation:", np.std(mat))

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Mittelwert: 5.0
Standardabweichung: 2.581988897471611


In [ ]:
arr = np.array([12, 15, 20, 10, 8, 13])
print("mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print(arr + 5)

Mittelwert: 13.0
Standardabweichung: 3.8297084310253524
[17 20 25 15 13 18]


In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr1d = np.array([1,2,3])
print(mat + arr1d) # Broadcasting on lines



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
arr5 = np.arange(12).reshape(3,4) # From 0 to 11. 3 rows with 4 entries each
print(arr5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Exercise: Basic arithmetic operations & statistics in NumPy

arr = np.random.randint(1, 10, size = (3,4))  # 3 rows, 4 columns
print(arr)
print("square **2:\n", arr ** 2)

print("Overall mean:", np.mean(arr))
print("Average per column:", np.mean(arr, axis=0))
print("Average per line:", np.mean(arr, axis=1))

print("sum total:", np.sum(arr))
print("minimum:", np.min(arr))
print("maximum:", np.max(arr))




[[8 7 1 4]
 [1 8 2 9]
 [4 4 9 7]]
Quadrat **2:
 [[64 49  1 16]
 [ 1 64  4 81]
 [16 16 81 49]]
Mittelwert gesamt: 5.333333333333333
Mittelwert pro Spalte: [4.33333333 6.33333333 4.         6.66666667]
Mittelwert pro Zeile: [5. 5. 6.]
Summe gesamt: 64
Minimum: 1
Maximum: 9


In [ ]:
import numpy as np
arr = np.random.randint(1, 21, size = (3,5))
print(arr)
print("Average per line:\n", np.mean(arr, axis=1))
print("Standard deviation per column:\n", np.std(arr, axis=0))
print("total:", np.sum(arr))

[[ 6 16 12 19 17]
 [11 17 12  7  4]
 [ 7  4  3 17  7]]
Mittwelert pro Zeile:
 [14.  10.2  7.6]
Standardabweichung pro Spalte:
 [2.1602469  5.90668172 4.24264069 5.24933858 5.55777733]
Gesamtsumme: 159
