In [2]:
import torch

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

z = x + y
z



tensor([5, 7, 9])

In [3]:
a = torch.randn(5,3)
b = torch.randn(5,3)

c = a + b
c

tensor([[-1.0796,  0.4176, -1.0249],
        [-0.1876,  1.1912,  1.5639],
        [ 1.5589, -1.0740, -0.0898],
        [-2.9198, -0.2564, -0.9655],
        [ 1.4255, -0.5810, -1.7157]])

In [4]:
x = torch.randn(5,3, requires_grad= True)
y = torch.randn(5,3)

z = x + y
out = z.mean()

out.backward()

x.grad

tensor([[0.0667, 0.0667, 0.0667],
        [0.0667, 0.0667, 0.0667],
        [0.0667, 0.0667, 0.0667],
        [0.0667, 0.0667, 0.0667],
        [0.0667, 0.0667, 0.0667]])

In [12]:
import torch
from torch.utils.data import Dataset, DataLoader

class SimpleDataSet(Dataset):
    def __init__(self):
        super().__init__()
        self.x = torch.linspace(-5,5,200).unsqueeze(1)
        self.y = self.x + 1
    
    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return {
            "x": self.x[index],
            "y": self.y[index]
        }
        
dataset = SimpleDataSet()


In [13]:
dataloader = DataLoader(dataset, batch_size=16, shuffle = True)

In [5]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(1,16),
    nn.ReLU(),
    nn.Linear(16,1))

In [6]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr= 0.01)


In [16]:
epochs = 20

for epoch in range(epochs):
    total_loss = 0

    for batch in dataloader:
        x_batch = batch["x"]
        y_batch = batch["y"]

        optimizer.zero_grad()


        outputs = model(x_batch)

    
        loss = criterion(outputs,y_batch)

        loss.backward()

        optimizer.step()

        total_loss += loss

    print(f"Epoche {epoch+1}/{epochs}, Loss = {total_loss:.4f}")

Epoche 1/20, Loss = 0.0142
Epoche 2/20, Loss = 0.0138
Epoche 3/20, Loss = 0.0135
Epoche 4/20, Loss = 0.0135
Epoche 5/20, Loss = 0.0124
Epoche 6/20, Loss = 0.0123
Epoche 7/20, Loss = 0.0120
Epoche 8/20, Loss = 0.0123
Epoche 9/20, Loss = 0.0124
Epoche 10/20, Loss = 0.0114
Epoche 11/20, Loss = 0.0114
Epoche 12/20, Loss = 0.0110
Epoche 13/20, Loss = 0.0109
Epoche 14/20, Loss = 0.0112
Epoche 15/20, Loss = 0.0106
Epoche 16/20, Loss = 0.0113
Epoche 17/20, Loss = 0.0113
Epoche 18/20, Loss = 0.0108
Epoche 19/20, Loss = 0.0098
Epoche 20/20, Loss = 0.0100
